-- MySQL Script generated by MySQL Workbench
-- Mo 04 Jan 2016 17:51:06 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `id_class` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `year` VARCHAR(45) NOT NULL COMMENT '',
  `letter` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_class`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id_student` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(45) NOT NULL COMMENT '',
  `lastname` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `klasse_idklasse` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_student`)  COMMENT '',
  INDEX `fk_schueler_klasse_idx` (`klasse_idklasse` ASC)  COMMENT '',
  CONSTRAINT `fk_schueler_klasse`
    FOREIGN KEY (`klasse_idklasse`)
    REFERENCES `mydb`.`class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `idsubject` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idsubject`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topic` (
  `idtopic` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `class_idclass` INT NOT NULL COMMENT '',
  `subject_idsubject` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtopic`)  COMMENT '',
  INDEX `fk_thema_klasse1_idx` (`class_idclass` ASC)  COMMENT '',
  INDEX `fk_thema_fach1_idx` (`subject_idsubject` ASC)  COMMENT '',
  CONSTRAINT `fk_thema_klasse1`
    FOREIGN KEY (`class_idclass`)
    REFERENCES `mydb`.`class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thema_fach1`
    FOREIGN KEY (`subject_idsubject`)
    REFERENCES `mydb`.`subject` (`idsubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_has_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_has_topic` (
  `student_id_student` INT NOT NULL COMMENT '',
  `topic_idtopic` INT NOT NULL COMMENT '',
  PRIMARY KEY (`student_id_student`, `topic_idtopic`)  COMMENT '',
  INDEX `fk_student_has_topic_topic1_idx` (`topic_idtopic` ASC)  COMMENT '',
  INDEX `fk_student_has_topic_student1_idx` (`student_id_student` ASC)  COMMENT '',
  CONSTRAINT `fk_student_has_topic_student1`
    FOREIGN KEY (`student_id_student`)
    REFERENCES `mydb`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_topic_topic1`
    FOREIGN KEY (`topic_idtopic`)
    REFERENCES `mydb`.`topic` (`idtopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studygroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studygroup` (
  `idstudygroup` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `day` VARCHAR(45) NULL COMMENT '',
  `time` VARCHAR(45) NULL COMMENT '',
  `room` VARCHAR(45) NULL COMMENT '',
  `topic_idtopic1` INT NOT NULL COMMENT '',
  `subject_idsubject` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idstudygroup`, `topic_idtopic1`, `subject_idsubject`)  COMMENT '',
  INDEX `fk_studygroup_topic1_idx` (`topic_idtopic1` ASC)  COMMENT '',
  INDEX `fk_studygroup_subject1_idx` (`subject_idsubject` ASC)  COMMENT '',
  CONSTRAINT `fk_studygroup_topic1`
    FOREIGN KEY (`topic_idtopic1`)
    REFERENCES `mydb`.`topic` (`idtopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studygroup_subject1`
    FOREIGN KEY (`subject_idsubject`)
    REFERENCES `mydb`.`subject` (`idsubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studygroup_has_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studygroup_has_student` (
  `studygroup_idstudygroup` INT NOT NULL COMMENT '',
  `student_id_student` INT NOT NULL COMMENT '',
  PRIMARY KEY (`studygroup_idstudygroup`, `student_id_student`)  COMMENT '',
  INDEX `fk_studygroup_has_student_student1_idx` (`student_id_student` ASC)  COMMENT '',
  INDEX `fk_studygroup_has_student_studygroup1_idx` (`studygroup_idstudygroup` ASC)  COMMENT '',
  CONSTRAINT `fk_studygroup_has_student_studygroup1`
    FOREIGN KEY (`studygroup_idstudygroup`)
    REFERENCES `mydb`.`studygroup` (`idstudygroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studygroup_has_student_student1`
    FOREIGN KEY (`student_id_student`)
    REFERENCES `mydb`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;"
